### ISSUE TITLE
[Feature Request] - Transition to OpenSSL 3.0

### ISSUE THREAD

**Issue by stewartsmith** [amazonlinux/amazon-linux-2022#10]
The current AL2022 preview is based on OpenSSL 1.1. This issue is to track our migration to an OpenSSL 3.0 base.

**Comment by mattdm** [comment]
Hi Amazon Linux team! Here is the Fedora Change proposal related to this https://fedoraproject.org/wiki/Changes/OpenSSL3.0 

The change was originally targeted at F33, but we've deferred it several times. We are currently planning to land this before the F36 branch at the beginning of February, with a contingency plan to for F37 if that doesn't work out. You can see the tracker bug (linked from that Change) at https://bugzilla.redhat.com/show_bug.cgi?id=1825937.

**Comment by skyzyx** [comment]
Question: Is the use of OpenSSL based on Fedora’s usage? Have forks such as LibreSSL or BoringSSL been evaluated? After Heartbleed, both of these forks occurred in an effort to slim-down the variables and focus primarily on modern systems while eschewing older systems.

I'm mostly just curious — I don't feel strongly either way. But since Amazon maintains its own distribution, I thought it'd be a reasonable question to ask.

**Comment by stewartsmith** [comment]
`2022.0.20220315` now has OpenSSL 3.0 - we're still transitioning some packages across to building against 3.0 rather than 1.1 though.
