### ISSUE TITLE
[Bug] - ARM64 AMI not accessible after EC2 instance launch

### ISSUE THREAD

**Issue by sktomer** [amazonlinux/amazon-linux-2022#101]
**Describe the bug**
In a considerable percentage (~15%) of cases, we are observing that Amazon Linux 2022 ARM64 AMIs are failing at the network configuration phase post EC2 instance launch. As such the launched instance fails instance status checks and is not accessible. This is an initial launch issue and does not affect running instances.

**To Reproduce**
1. Go to AWS EC2 console using your AWS account
2. Click on Instances -> Launch Instance and select an AL 2022 ARM64 AMI (from Public Images)
3. Configure other instance launch settings as usual using the instance launch wizard
4. Repeat steps until you get an EC2 instance that fails instance status checks and is not accessible

**Expected behavior**
EC2 instance launches should be always successful for Amazon Linux 2022 AMIs

**Additional context**
This issue is known to the Amazon Linux team and we are actively working to find a solution.
Until this is addressed, we will not be publishing new Amazon Linux 2022 ARM64 Tech Preview AMIs.

Meanwhile we will continue to release Amazon Linux 2022 x86_64 Tech Preview AMIs with the latest updates.

If you wish to use AL 2022 ARM64 AMIs, you can still do so by launching the existing AMIs.
You can also run the following command to update your existing EC2 instance with the latest updates:

`$ sudo dnf update --releasever <version>`

For more details, please visit this [page](https://docs.aws.amazon.com/linux/al2022/ug/version-locking.html).
The available release versions can be obtained by running:

`$ dnf check-release-update`

**Comment by liesenml** [comment]
Hello, thank you for submitting your request! We review all requests on a weekly basis and will reply to this ticket by with our evaluation.

**Comment by omgoo** [comment]
At MirrorWeb we also saw this issue when testing the AL2022 ARM ami back in February. Launching over 1000 servers automatically for web crawls we saw a failure rate that was around the 15% stated in this bug. We abandoned further testing after the launch failures so I'm watching this bug with interest.

**Comment by PlaidCat** [comment]
Hello everyone and thank you for your patience,

There is a mitigation rolling out with the `AL 2022.0.20220504.1` release. 

What we observed is that `/boot/efi` failed to mount and fell to emergency mode (only accessible via serial console).
In a SystemD v250+ the behavior changes to not fall to emergency mode, but never mounts `/boot/efi`.

Mitigation adds `x-systemd.automount` to the `/boot/efi` `/etc/fstab` entry and will get mounted when that path is accessed.

This worked on 500+ instance launch tests with AL2022 AMIs using SystemD v248.10, v250.3, and Mainline builds.
We successfully mount `/boot/efi` device when we run `ls /boot/efi`.

We do not have a root cause, but we are actively working with the SystemD community on their 2.5yr old open issue here: https://github.com/systemd/systemd/issues/13775

Our leading theory is there is a race condition with `Systemd-udevd` and SystemD state changes (reloads) like when doing an InitRD pivot, and then the new reload does not recognize the correct unit dependencies.

This theory could change as debugging in the SystemD Issue continues.
