### ISSUE TITLE
[Bug] - Intermittent DNS Resolution

### ISSUE THREAD

**Issue by cellsignal-m** [amazonlinux/amazon-linux-2022#137]
**Describe the bug**
We see that when we call for a DNS request, it will from time to time - timeout and not provide a result.
If we restart the system, the issue goes away.

**To Reproduce**
1. Do a ping to a known host.
2. We sometimes get a resolution and response and sometimes get a no response 

**Expected behavior**
Resolution should work each and every time.

**Screenshots**
See image in comments below

**Server (please complete the following information):**
 - OS: Amazon Linux 2022

**Additional context**

**Comment by cellsignal-m** [comment]
![dnsresolvissue](https://user-images.githubusercontent.com/103438525/178272544-c5375358-bda3-4f87-88f8-d09c7eaec057.png)

**Comment by cellsignal-m** [comment]
We noticed that it seems to fail when DNS resolves to 3.5.21.193

**Comment by stewartsmith** [comment]
This doesn't seem to be anything related to the Amazon Linux 2022 host though, as the included screenshot is Windows, and there's not any information here to link this to an issue with the possible host on the other end.

If there's some information that can be provided that narrows this down to an AL2022 issue rather than some local routing issue, please do add more information.
