### ISSUE TITLE
[Feature Request] - Simple way to fetch the release version

### ISSUE THREAD

**Issue by paulcacheux** [amazonlinux/amazon-linux-2022#209]
**Is your feature request related to a problem? Please describe.**
I'm looking for a simple way to query the release version of a running amazon linux 2022 system. I'm aware that `rpm -qi system-release` gives me what I'm looking for but it actually involves a query to the rpmdb.

My end goal is to be able, from a docker container with only a `/etc:/host/etc` volume, to fetch the release version of the host amazon linux, so querying the DB manually is out of the picture.

**Describe the solution you'd like**
Most other distributions provide the release version in `/etc/os-release`, maybe you could provide the whole version like `2022.0.20220928` instead of `2022` in the `VERSION` field ?

**Describe alternatives you've considered**
I have considered the `rpm` solution.

**Additional context**
N/A

Thank you very much in advance

**Comment by stewartsmith** [comment]
There is `/etc/image-id` - but that is created at image creation time, and AFAIK not updated with any future system update, so that would only partially solve this problem. I think there's a CPE field we could use though, and thus that could be a way forward. We'll look into it and see what we can do, as it's certainly a valid use case.

**Comment by paulcacheux** [comment]
`/etc/image-id` is a good idea and what I will be using for the time being. Thank you for answering !
