### ISSUE TITLE
[Feature Request] - reconsider the return of `amazon-linux-extras`

### ISSUE THREAD

**Issue by daniejstriata** [amazonlinux/amazon-linux-2022#236]
**Is your feature request related to a problem? Please describe.**
@stewartsmith Please reconsider that `amazon-linux-extras` script. It is such a valuable tool. It helped me install all different and current releases which I would not have known are available on AMZN2 like postgres, Python 3.8 and importantly the newer 5.15 kernels.

Whereas the AMZN script enabled extra repos, the AL2022 version could manage / display used modules.

1. If would be quite easy to have a similar script which lists the different available dnf modules and simply assist switching between / enabling the different versions. 

2. It can also help enabling LivePatch by running all the steps in the correct sequence to enable LivePatch.

**Describe the solution you'd like**
Essentially listing and helping to switch dnf modules and correctly enable LivePatch.

**Comment by stewartsmith** [comment]
Rather than enabling separate repositories, we are providing different versions of packages via namespacing them. This means you can (for example) `dnf install python3.10` to get a `/usr/bin/python3.10` and choose between different versions of packages such as PostgreSQL.

We found that this method gives more flexibility and less complexity.

**Comment by daniejstriata** [comment]
@stewartsmith I'm looking forward to the idea. I'm just hoping you present those different packages as easily as it was with `amazon-linux-extras`. I've failed to really utilize streams in RHEL8 mostly because I was never presented with the knowledge that there is a newer version.
