### ISSUE TITLE
[Package Request] - Linux 5.15

### ISSUE THREAD

**Issue by stewartsmith** [amazonlinux/amazon-linux-2022#4]
The initial preview AMIs contain a 5.10 based kernel, similar to what we provide in the kernel-5.10 Amazon Linux 2 Extra repository. The next LTS kernel is 5.15, and this will become the kernel for Amazon Linux 2022.

**Comment by njacklin1988** [comment]
This is available in the AL2022 repos. AMI coming shortly.

**Comment by aran112000** [comment]
@njacklin1988, given the time since this was merged, will the kernel version be updated again prior to launch as 5.15 has a projected EOL less than a year away already, and 6.1 is rumoured to be the next LTS release expected in the next month, with a lot of major improvements in there from a power usage and performance perspective thanks to scheduler improvements.
